// src/contentScripts/views/App.tsx
import { useRef, useState } from 'react'
import { asType } from '@wai-ri/core'
import 'virtual:windi.css'


export default function App() {
  const [showBtn, setShowBtn] = useState(true)
  const [resultText, setResultText] = useState('')
  const [showTranslate, setShowTranslate] = useState(false)
  const [tranlationText, setTranlationText] = useState('')
  const [topVal, setTopVal] = useState(0)
  const [leftVal, setLeftVal] = useState(0)
  const rootEl = useRef<HTMLDivElement>(null)

  document.addEventListener('pointerup', (event) => {
    asType<NonNullable<typeof rootEl.current>>(rootEl.current)

    if (event.button !== 0) return
    if (rootEl.current.contains(event.target as HTMLDivElement)) return

    const selection = document.getSelection()
    if (!selection) return
    const text = selection.toString()
    if (text === '') return setShowTranslate(false)

    setShowTranslate(true)
    setShowBtn(true)

    setTranlationText(text)
    setResultText('')

    const { clientX, clientY } = event
    setTopVal(clientY)
    setLeftVal(clientX)
  })

  function onTraslate(event: MouseEvent) {
    event.stopPropagation()
    setShowBtn(false)
    fetch(
      'https://api.66mz8.com/api/translation.php?info=' + encodeURIComponent(tranlationText),
      { mode: 'cors', method: 'POST' }
    )
      .then(res => res.json())
      .then(result => {
        if (result.code !== 200) return Promise.reject()
        setResultText(result.fanyi)
      })
      .catch(err => setResultText('翻译时出错'))
  }

  return (
    <div ref={rootEl} style={{ display: showTranslate ? 'block' : 'none' }}>
      <div className='fixed' style={{ top: `${topVal}px`, left: `${leftVal}px` }}>
        {showBtn
          ? <button onClick={onTraslate as any}>翻译</button>
          : <div className="bg-light-50 shadow-sm text-black"> {resultText || "翻译中..."} </div>
        }
      </div>
    </div>
  )
}

// src/contentScripts/views/App.vue
<script setup lang="ts">
import { useEventListener, onClickOutside } from '@vueuse/core'
import { asType } from '@wai-ri/core'
import 'virtual:windi.css'

const topVal = ref(0)
const leftVal = ref(0)
const rootEl = ref<HTMLDivElement>()
const showTranslate = ref(false)
const tranlationText = ref('')
const resultText = ref('')
const showBtn = ref(true)

useEventListener(document, 'pointerup', (e) => {
  asType<NonNullable<typeof rootEl.value>>(rootEl.value)

  if (e.button !== 0) return
  if (rootEl.value.contains(e.target as HTMLDivElement)) return

  const selection = document.getSelection()
  if (!selection) return
  const text = selection.toString()
  if (text === '') return showTranslate.value = false


  showTranslate.value = true
  showBtn.value = true

  tranlationText.value = text
  resultText.value = ''

  const { clientX, clientY } = e
  topVal.value = clientY
  leftVal.value = clientX
})

function onTraslate(e: MouseEvent) {
  e.stopPropagation()
  showBtn.value = false
  fetch(
    'https://api.66mz8.com/api/translation.php?info=' + encodeURIComponent(tranlationText.value),
    { mode: 'cors', method: 'POST' }
  )
    .then(res => res.json())
    .then(result => {
      if (result.code !== 200) return Promise.reject()
      resultText.value = result.fanyi
    })
    .catch(e => resultText.value = '翻译时出错')
}



</script>

<template>
  <div
    v-show="showTranslate"
    ref="rootEl"
  >
    <div
      class="fixed"
      :style="{ top: `${topVal}px`, left: `${leftVal}px` }"
    >
      <button
        v-if="showBtn"
        @click.stop="onTraslate"
      >
        翻译
      </button>
      <div
        v-else
        class="bg-light-50 shadow-sm text-black"
      >
        {{ resultText || '翻译中...' }}
      </div>
    </div>
  </div>
</template>


<style scoped>
</style>
